name: Versioning

on:
  pull_request:
    types:
      - closed

jobs:
  update_version_and_changelog:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Determine version bump
        id: get_version_bump
        run: |
          branch_name=${{ github.event.pull_request.head.ref }}
          if [[ $branch_name == major/* || $branch_name == release/* ]]; then
            echo "bump=major" >> $GITHUB_ENV
          elif [[ $branch_name == minor/* || $branch_name == feature/* || $branch_name == task/* || $branch_name == refactor/* || $branch_name == poc/* || $branch_name == innovation/* ]]; then
            echo "bump=minor" >> $GITHUB_ENV
          elif [[ $branch_name == patch/* || $branch_name == bug/* || $branch_name == doc/* || $branch_name == tools/* || $branch_name == hotfix/* ]]; then
            echo "bump=patch" >> $GITHUB_ENV
          else
            echo "bump=patch" >> $GITHUB_ENV
          fi

      - name: Update version.txt
        run: |
          version=$(cat version.txt)
          bump="${{ steps.get_version_bump.outputs.bump }}"
          
          if [[ $bump == "major" ]]; then
            new_version=$(echo $version | awk -F. '{$1 = $1 + 1; $2 = 0; $3 = 0;} 1' OFS=.)
          elif [[ $bump == "minor" ]]; then
            new_version=$(echo $version | awk -F. '{$2 = $2 + 1; $3 = 0;} 1' OFS=.)
          else
            new_version=$(echo $version | awk -F. '{$3 = $3 + 1;} 1' OFS=.)
          fi
          
          echo $new_version > version.txt

      - name: Update CHANGELOG.md
        run: |
          new_version=$(cat version.txt)
          awk -v ver="$new_version" -v title="${{ github.event.pull_request.title }}" '{
            print;
            if (NR==1) {
              print "\n## " ver "\n* " title "\n";
            }
          }' CHANGELOG.md > CHANGELOG.tmp && mv CHANGELOG.tmp CHANGELOG.md

      - name: Set up Git with PAT, Commit and push
        run: |
          git config --local user.email "sugalvojau@gmail.com"
          git config --local user.name "GitHub Action"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}
          git add CHANGELOG.md version.txt
          git commit -m "Update CHANGELOG.md and version.txt"
          git push
