name: Versioning

on:
  pull_request:
    types:
      - closed

jobs:
  update_version_and_changelog:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Determine version bump
        id: get_version_bump
        run: |
          branch_name=${{ github.event.pull_request.head.ref }}
          if [[ $branch_name == major/* ]]; then
            echo "::set-output name=bump::major"
          elif [[ $branch_name == minor/* ]]; then
            echo "::set-output name=bump::minor"
          elif [[ $branch_name == patch/* ]]; then
            echo "::set-output name=bump::patch"
          else
            echo "::set-output name=bump::patch" # default to patch if no recognized prefix
          fi

      - name: Update version.txt
        run: |
          version=$(cat version.txt)
          bump="${{ steps.get_version_bump.outputs.bump }}"
          
          if [[ $bump == "major" ]]; then
            new_version=$(echo $version | awk -F. '{$1 = $1 + 1; $2 = 0; $3 = 0;} 1' OFS=.)
          elif [[ $bump == "minor" ]]; then
            new_version=$(echo $version | awk -F. '{$2 = $2 + 1; $3 = 0;} 1' OFS=.)
          else
            new_version=$(echo $version | awk -F. '{$3 = $3 + 1;} 1' OFS=.)
          fi
          
          echo $new_version > version.txt

      - name: Update CHANGELOG.md
        run: |
          new_version=$(cat version.txt)
          echo "## $new_version" >> CHANGELOG.md
          echo "* ${{ github.event.pull_request.title }}" >> CHANGELOG.md
          echo "" >> CHANGELOG.md

      - name: Commit and push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add CHANGELOG.md version.txt
          git commit -m "Update CHANGELOG.md and version.txt"
          git push
